const mongoose=require('mongoose')
const postSchema=new mongoose.Schema({
    userId:mongoose.Schema.Types.ObjectId,
    username:String,
    profilePicture:{
        type:String,
        default:""
    },
    name:{
        type:String,
        default:""
    },
    caption:{
        type:String,
        default:""
    },
    imageUrl:{
        type:Array,
        default:[]
    },
    imageId:{
        type:Array,
        default:[]
    },
    language:{
        type:Array,
        default:[]
    },
    codeSnippet:{
        type:Array,
        default:[]
    },
    tags:{
        type:Array,
        default:[]
    },
    likes:{
        type:Number,
        default:0
    },
    comments:{
        type:Number,
        default:0
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
})
module.exports=mongoose.model('Post',postSchema);